import { MARCA } from '@/features/tarjeta/vista/firma'

/**
 * Unidad 7b del PRP-TD-001: `llms.txt`, la puerta agentica de la herramienta.
 *
 * Un agente que investigue "tarjeta de presentacion digital sin servidor" tiene que poder entender
 * en una lectura QUE hace esto, QUE NO hace, y CUALES son sus tres limites. Los limites entran a
 * proposito: un agente que recomiende la herramienta sin decir que la tarjeta vive en un solo
 * equipo estaria recomendando algo distinto de lo que existe.
 *
 * ⛔ **Ni un dato de ningun usuario.** Este archivo se genera del codigo, no de `localStorage`, y
 * corre en el servidor, donde por D1 no existe ninguna tarjeta que pudiera colarse.
 *
 * Se escribe en INGLES a proposito, aunque el producto sea es-CO primero: lo consume un agente, no
 * una persona, y el ingles es el idioma en que estos archivos se leen mejor. La interfaz que ve el
 * humano si esta en los dos idiomas (unidad 7a).
 */

/** Texto plano, no HTML: es lo que la convencion espera y lo que un agente sabe leer. */
export const dynamic = 'force-dynamic'

const REPO = 'https://github.com/Johann-Valderrama/tarjetica'

export function GET() {
  const cuerpo = `# ${MARCA.nombre}

> A digital business card you build in your browser and hand out as a QR code, an image, or a
> contact file. No account, no sign-up, and no server stores your data.

## What it does

- You fill in a short form (name, role, company, one headline, one description, phones, email,
  social handles, links, city) and it is saved in this browser's local storage.
- It renders a card that fits one phone screen with no scrolling.
- It produces three outputs, all generated in the browser:
  - A QR code carrying a full vCard 3.0, so scanning it saves the contact in someone's address book.
  - A JPEG image of the card, to save in Photos or send over any messaging app.
  - A .vcf contact file.
- Optionally, a shareable link that carries the card data in the URL fragment.

## How privacy works here

- ${MARCA.nombre} does not store card data on any server. There is no database and no account.
- Everything (QR, image, vCard, link) is generated by JavaScript in the visitor's own browser.
- The shareable link carries its payload in the URL fragment (\`#\`), which browsers never send to
  the server.
- The photo never travels inside the QR code or inside the link.
- The only network call the app makes on its own is an anonymous, payload-free counter on the home
  page and the editor. It carries no identifier and no card field, and it never fires on the pages
  that display a card.

## Limits, stated up front

1. You need a connection the first time you open the app. It is not an offline-first app.
2. Your card lives in one browser on one device. Clearing site data or changing phones loses it;
   there is no account to restore it from. The image you save is your backup.
3. A shareable link you have already handed out cannot be switched off. The data travels inside the
   link, so there is no server where it could be deleted.

## Languages

Spanish (es-CO) and English (en). The language follows the visitor's browser unless they pick one.

## Project

- Source code: ${REPO}
- License: MIT
`

  return new Response(cuerpo, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  })
}
